### ISSUE TITLE
Document not well displayed in dataseer-web

### ISSUE THREAD

**Issue by NicolasKieffer** [DataSeer/dataseer-ml#9]
@kermitt2 
A document is not well displayed in dataseer-web:

[URL](https://cloud.science-miner.com/dataseer-dev/documents/60490c6f75029b59e25650e0) and [PDF file](https://cloud.science-miner.com/dataseer-dev/api/documents/60490c6f75029b59e25650e0/pdf/content) of concerned document

**Comment by kermitt2** [comment]
@NicolasKieffer 
The links are not working any more. 

Was it the case with line numbers not filtered out in the selected areas?

**Comment by NicolasKieffer** [comment]
[New link](https://app.dataseer.ai/dataseer/documents/605e1d0c503b2e2239d32d81) to the document (previous do not work because data on dev-server often change).

**Comment by kermitt2** [comment]
Thanks !!
Is there an easy link to the corresponding PDF?

**Comment by NicolasKieffer** [comment]
[PDF Link here](https://app.dataseer.ai/dataseer/api/documents/605e1d0c503b2e2239d32d81/pdf/content)

**Comment by NicolasKieffer** [comment]
URL updated (need to be logged in now)

**Comment by kermitt2** [comment]
super !

**Comment by kermitt2** [comment]
There is no error in the tokens, line numbers are indeed filtered out. 
I am looking at the sentence coordinates now. 

![Screenshot from 2021-04-05 19-25-50](https://user-images.githubusercontent.com/2340795/113604275-52bd9c80-9645-11eb-9f74-7ca5b1b23832.png)

![Screenshot from 2021-04-05 19-30-44](https://user-images.githubusercontent.com/2340795/113604349-7254c500-9645-11eb-801b-1ce2842f0941.png)

**Comment by kermitt2** [comment]
Problem seems to be an empty box just after the number at `4,60.12,270.91,5.74,11.49;` (width of the box only `5.74`) - it seems that the bounding boxes include this small box corresponding to a space character located apparently before the number... the number and its box are indeed well removed, but the spurious space character is not which gives this wrong global box.

**Comment by kermitt2** [comment]
Fixed via https://github.com/kermitt2/pdfalto/commit/865f229b3b122b1ea4498147efc9fb952b9bafed (normally!)

![Screenshot from 2021-04-05 21-54-06](https://user-images.githubusercontent.com/2340795/113619592-768add80-9659-11eb-9ac5-d3609dc3053b.png)

**Comment by NicolasKieffer** [comment]
Ok, the grouping of areas is done by the PDF viewer. It tries to group together the areas as much as possible to create the "enclosing" zone.
If necessary I can try to improve it.

**Comment by kermitt2** [comment]
Updated on the dev server:

![Screenshot from 2021-04-05 23-06-43](https://user-images.githubusercontent.com/2340795/113627344-a939d380-9663-11eb-867a-334b0d548f56.png)

It was an issue from pdfalto, better to fix it from the source.
